export const INITIAL_REVISION = 'REV01'

/**
 * Acronym = the first three letters of the name, uppercase, without accents.
 * "Tubulação" → "TUB", "Memória de Cálculo" → "MEM", "Revisão Técnica" → "REV".
 * The API already sends `acronym` for disciplines; this is used for the
 * static document-type list.
 */
export function toAcronym(name) {
  if (!name) return ''
  return String(name)
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .replace(/[^A-Za-z]/g, '')
    .slice(0, 3)
    .toUpperCase()
}

/**
 * Preview of the unique code in the pattern PROJETO-SUBGRUPO-TIPO-REV,
 * e.g. "PJT001-TUB-REV-REV01", built from `project.code`,
 * `discipline.acronym`, the document type acronym and the revision.
 * The definitive code is generated by the backend on submission; the
 * frontend only previews it (read-only). Returns null while any part is
 * still missing.
 */
export function buildDocumentCode({ project, discipline, type, revision = INITIAL_REVISION }) {
  const parts = [project, discipline, type, revision].map((p) => (p ?? '').toString().trim())
  if (parts.some((p) => p === '')) return null
  return parts.join('-').toUpperCase()
}
