export const INITIAL_REVISION = 'REV01'

/**
 * Sigla = the first three letters of the name, uppercase, without accents.
 * "Tubulação" → "TUB", "Memória de Cálculo" → "MEM", "Revisão Técnica" → "REV".
 */
export function toSigla(nome) {
  if (!nome) return ''
  return String(nome)
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^A-Za-z]/g, '')
    .slice(0, 3)
    .toUpperCase()
}

/**
 * Preview of the unique code in the pattern PROJETO-SUBGRUPO-TIPO-REV,
 * e.g. "PJT001-TUB-REV-REV01". The definitive code is generated by the
 * backend on POST /documentos; the frontend only previews it (read-only).
 * Returns null while any part is still missing.
 */
export function buildDocumentCode({ projeto, disciplina, tipo, revisao = INITIAL_REVISION }) {
  const parts = [projeto, disciplina, tipo, revisao].map((p) => (p ?? '').toString().trim())
  if (parts.some((p) => p === '')) return null
  return parts.join('-').toUpperCase()
}
