/** Documents are created at version 1; the backend stores the version as an integer. */
export const INITIAL_VERSION = 1

/** User-facing revision label for a version number: 1 → "REV01". */
export function revisionLabel(version = INITIAL_VERSION) {
  return `REV${String(version).padStart(2, '0')}`
}

/**
 * Preview of the unique code in the pattern PROJECT-DISCIPLINE-TYPE-REV,
 * e.g. "AK-2100-EST-DWG-REV01", built from `project.code`, `discipline.code`,
 * the document type code and the version. Nothing is derived from names:
 * every code comes from the database or the static catalogs.
 * The definitive code is generated by the backend on submission; the
 * frontend only previews it (read-only). Returns null while any part is
 * still missing.
 */
export function buildDocumentCode({ project, discipline, type, version = INITIAL_VERSION }) {
  const parts = [project, discipline, type].map((p) => (p ?? '').toString().trim())
  if (parts.some((p) => p === '')) return null
  return [...parts, revisionLabel(version)].join('-').toUpperCase()
}
